### ISSUE TITLE
Cloning fails when requesting specific commit

### ISSUE THREAD

**Issue by aplzr** [jmnavarrol/python-multigit#13]
Using multigit 0.11.6 and this `subrepos` file:

```yaml
subrepos:
- repo: https://github.com/dslaborg/sumo
  path: sumobase
  commit: '4a5ac7e8c1e2fcdb774a9e3c5f420af565e9c613'
```

I get the following error message after `multigit --run`:

```
repository: 'https://github.com/dslaborg/sumo'                                                               
requested commit: '4a5ac7e8c1e2fcdb774a9e3c5f420af565e9c613'                                                 
status: ERROR                                                                                                
extra info: 'Cloning into '[redacted]'...
        POST git-upload-pack (568 bytes)                                                                     
        fatal: Remote branch 4a5ac7e8c1e2fcdb774a9e3c5f420af565e9c613 not found in upstream origin           
        '                                                                                                    
```

The error message suggests that multigit might be looking for a branch instead of a commit. Not specifying a commit or specifying a branch both work as expected.
