### ISSUE TITLE
How do I add private repos?

### ISSUE THREAD

**Issue by batmanscode** [jmnavarrol/python-multigit#4]
Hi, a huge thank you for putting this together! I have just come across this problem in my programming journey and found submodules and subtrees unnecessarily complex.

What is a simple way to add a private repo?

**Comment by jmnavarrol** [comment]
Hello:

Nothing special.  You just need to add the same string you'd use when cloning it from command line.  I.e.:

```yaml
subrepos:
- path: 'projects/subproject'
  repo: 'ssh://user@private.server:8128/jmnavarrol/subproject.git'
  branch: 'master'
```

Can you offer a specific case of what you are trying to accomplish?

**Comment by jmnavarrol** [comment]
I suppose you already figured it out, so closing this.

**Comment by batmanscode** [comment]
Thank you @jmnavarrol!

Sorry for the delay, I missed the notification 🥲

What I was trying to do:
Include repo1 in repo2, both are private. Submodules would've allowed me to do this but seemed unnecessary, then I found your project!

What I ended up doing:
Instead of creating repo2, I added a folder to repo1 (so a "monorepo").

**Comment by jmnavarrol** [comment]
So do you mean two levels depth? Like...
```
baserepo/.git
        |-one-subdir/.git
             |-another-subdir/.git
```

If that's the case, you should only remember that the subrepos' definition file holds an array, so it's sorted.  Just declare your "deeper" repo below your "shallower" one, like this:
```yml
subrepos:
- path: 'one-subdir'
  repo: 'git@github.com:some/repo.git'
- path: 'one-subdir/another-subdir'
  repo: 'git@github.com:someother/repo.git'
```

Alternatively you could have a subrepos file in the topmost repo only declaring the first path and then another subrepos file in the intermediate repo declaring the deepest one.
In baserepo:
```yml
subrepos:
- path: 'one-subdir'
  repo: 'git@github.com:some/repo.git
```
And then, in github.com:some/repo.git:
```yml
subrepos:
- path: 'another-subdir'
  repo: 'git@github.com:someother/repo.git'
```

Hope this helps.
